### ISSUE TITLE
File adapter ?

### ISSUE THREAD

**Issue by gedw99** [vlcn-io/docs#1]
The CRDT / change-sets are designed for graph based data bases. SQLite and the ORM your working on.

I am working on an IDL that is line based and so git friendly but also CRDT / change-sets friendly.

So I was thinking how can I sync the IDL ?

1. File Adapter to store each file in the web file system. 
2. Store each line in SQLite lite.

Option 1 feels like the right solution to me. 

Do you have any thoughts on this ? 

—-

image blobs could also use the same approach.

Treat them like git lfs. The FS holds a pointer to the real location of the imsge. 

The IDL references  image resources via a uri pointer and the has access to them. 

This opens up the ability to edit code and images in the browser using wasm.  The IDL glues them together and renders the gui to the browser window .

**Comment by tantaman** [comment]
I think I need some more context.

IDL = interface definition language?

Is the idea that many people can edit the same IDL and you want to merge changes to that IDL? Or is the IDL immutable and you just want every user to receive a copy of it?
