### ISSUE TITLE
Caniuse 

### ISSUE THREAD

**Issue by gedw99** [vlcn-io/docs#2]
IOS is still a no show .

should we mention that in the docs with this link ?

https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility

**Comment by tantaman** [comment]
Here's an example of the lack of concurrency of the official SQLite wasm port.

https://github.com/vlcn-io/cr-sqlite/pull/56#issue-1458679617

The top video is the wasm build we're using (wa-sqlite) the bottom is the official one.

**Comment by gedw99** [comment]
Now it makes sense .

Thanks @tantaman
