### ISSUE TITLE
RSS feed from blog

### ISSUE THREAD

**Issue by agg23** [vlcn-io/docs#8]
I have been watching the project for a while, and it would be great to automatically be notified as you add new articles to the blog via a RSS feed. Not sure how big of an ask this is given your "blog" is just arbitrary documents, but it would be nice to have.

**Comment by tantaman** [comment]
deploying these two -- ebd9299ab872fd945e2c5cdddf713e8d57a5fe4a & d13f5df63a38ade9767b6f7762d702391fbc0e6f

which should do the trick.

**Comment by tantaman** [comment]
https://vlcn.io/blog/rss.xml

**Comment by agg23** [comment]
Fantastic! Thanks
